import React from "react";
import { Product } from "../product";

export /*bundle*/ const Clothes = () => {
    return(
        <>
            <Product 
                product='Shirt'
                brand='None'
                price='15$'
                src='images/images-shop-real/ropas/camisa-azul.png'
                categories='clothes'
            />
            <Product 
                product='Shirt'
                brand='None'
                price='15$'
                src='images/images-shop-real/ropas/camisa-hombre.png'
                categories='clothes'
            />
            <Product 
                product='Vest'
                brand='None'
                price='20$'
                src='images/images-shop-real/ropas/chaleco-tipo-ingeniero.png'
                categories='clothes'
            />
            <Product 
                product='Cap'
                brand='Fresh'
                price='35$'
                src='images/images-shop-real/ropas/gorra-fresh.png'
                categories='clothes'
            />
            <Product 
                product='Cap'
                brand='Nike'
                price='30$'
                src='images/images-shop-real/ropas/gorra-nike.png'
                categories='clothes'
            />
            <Product 
                product='Jeans'
                brand='None'
                price='15$'
                src='images/images-shop-real/ropas/jeans-damas.png'
                categories='clothes'
            />
            <Product 
                product='Pants'
                brand='None'
                price='20$'
                src='images/images-shop-real/ropas/pantalones-verdes.png'
                categories='clothes'
            />
            <Product 
                product='Shoes'
                brand='Jordan'
                price='40$'
                src='images/images-shop-real/ropas/zapatos-jordan.png'
                categories='clothes'
            />
            <Product 
                product='Shoes'
                brand='Kondor'
                price='25$'
                src='images/images-shop-real/ropas/zapatos-kondor.png'
                categories='clothes'
            />
        </>
    )
}    